/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthCheckRouteImport } from './routes/healthCheck'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiEmailSignupRouteImport } from './routes/api/email-signup'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAdminRouteImport } from './routes/api/admin'

const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/healthCheck',
  path: '/healthCheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSignupRoute = ApiEmailSignupRouteImport.update({
  id: '/api/email-signup',
  path: '/api/email-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/healthCheck': typeof HealthCheckRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email-signup': typeof ApiEmailSignupRoute
  '/api/session-status': typeof ApiSessionStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/healthCheck': typeof HealthCheckRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email-signup': typeof ApiEmailSignupRoute
  '/api/session-status': typeof ApiSessionStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/healthCheck': typeof HealthCheckRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/chat': typeof ApiChatRoute
  '/api/email-signup': typeof ApiEmailSignupRoute
  '/api/session-status': typeof ApiSessionStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/healthCheck'
    | '/api/admin'
    | '/api/chat'
    | '/api/email-signup'
    | '/api/session-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/healthCheck'
    | '/api/admin'
    | '/api/chat'
    | '/api/email-signup'
    | '/api/session-status'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/healthCheck'
    | '/api/admin'
    | '/api/chat'
    | '/api/email-signup'
    | '/api/session-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HealthCheckRoute: typeof HealthCheckRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEmailSignupRoute: typeof ApiEmailSignupRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/healthCheck': {
      id: '/healthCheck'
      path: '/healthCheck'
      fullPath: '/healthCheck'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-signup': {
      id: '/api/email-signup'
      path: '/api/email-signup'
      fullPath: '/api/email-signup'
      preLoaderRoute: typeof ApiEmailSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HealthCheckRoute: HealthCheckRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEmailSignupRoute: ApiEmailSignupRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
